version: '3.9'

name: onconcert

networks:
  default:
    name: onconcert-app-network

volumes:
  mssql_server_data:
    name: onconcert-data

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=sa
      - SA_PASSWORD=WeOnN0@!R#
      - MSSQL_DB_NAME=onconcert
      - MSSQL_PID=Developer
    volumes:
      - mssql_server_data:/var/opt/mssql
